//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchMemberProfile.WebAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberProfilePropertyValue
    {
        public int RecordID { get; set; }
        public int MemberId { get; set; }
        public int PropertyID { get; set; }
        public string Value { get; set; }
        public byte IsDeleted { get; set; }
    
        public virtual MemberProfile MemberProfile { get; set; }
    }
}
