//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchMemberProfile.WebAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberProfile
    {
        public MemberProfile()
        {
            this.MemberProfilePropertyValues = new HashSet<MemberProfilePropertyValue>();
        }
    
        public int RecordID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string MI { get; set; }
        public string Nickname { get; set; }
        public System.DateTime Birthdate { get; set; }
        public Nullable<int> LeaderId { get; set; }
        public string Address { get; set; }
        public int Template { get; set; }
    
        public virtual ICollection<MemberProfilePropertyValue> MemberProfilePropertyValues { get; set; }
    }
}
